In [1]:
import numpy as np
import math

# TEST
$h_1=0$ 

In [2]:
def relu(z, deriv=False):
    activations = []
    shape = z.shape
    z = z.flatten()
    if deriv:
        for i in range(len(z)):
            if z[i] >= 0:
                activations.append(1)
            else:
                activations.append(0)
        return np.array(activations).reshape(shape)
    for i in range(len(z)):
        if z[i] > 0:
            activations.append(z[i])
        else:
            activations.append(0)
    return np.array(activations).reshape(shape)

In [79]:
def reset():
    global w, b
    w = [
        np.array(np.random.rand(6)).reshape(2,3),
        np.array(np.random.rand(9)).reshape(3,3),
        np.array(np.random.rand(6)).reshape(3,2),
        np.array(np.random.rand(2)).reshape(2,1)
    ]
    b = [
        np.array([np.zeros(3)]),
        np.array([np.zeros(3)]),
        np.array([np.zeros(2)]),
        np.array([np.zeros(1)])
    ]

# [previous, neuron_count]
w = [
    np.array(np.random.rand(6)).reshape(2,3),
    np.array(np.random.rand(9)).reshape(3,3),
    np.array(np.random.rand(6)).reshape(3,2),
    np.array(np.random.rand(2)).reshape(2,1)
]
b = [
    np.array([np.random.rand(3)]),
    np.array([np.random.rand(3)]),
    np.array([np.random.rand(2)]),
    np.array([np.random.rand(1)])
]

for i in w: print(i)

[[0.34535875 0.46916952 0.18472229]
 [0.43623386 0.69973803 0.34003479]]
[[0.37886188 0.39378201 0.22016079]
 [0.40543993 0.53455279 0.69302586]
 [0.44018559 0.53531516 0.10661116]]
[[0.88913152 0.49103421]
 [0.24365102 0.11397508]
 [0.35173607 0.79227154]]
[[0.70866006]
 [0.94313261]]


In [4]:
np.array([[0,1]]) @ w[0]

array([[0.6657651 , 0.58009577, 0.14212619]])

In [5]:
z = [
    
]
a = [
    
]


def forward_prop(X):
    h = X
    global a, z
    a,z  = [], []
    for i in range(len(w)):
        h = h @ w[i] # weigt * input
        h = h + b[i] # bias add
        z.append(h)
        h = relu(h) # Activation Function
        a.append(h)
    return h

forward_prop(np.array([0,1]))


array([1.70369917])

# Back Prop

for each layer

$g = loss'(X,y)$

## Step 1 ($a$ to $z$)

$g = relu'(z)$



## Step 2 ($z$ to $W$)

$g = relu'(z) * a_{L-1}$

# Dimensions

$g = [1\times2]$

## Step 1 Activation Function Derriv

$g = [1\times2]$


In [84]:
learning_rate = 0.02

reset()

def back_prop(X, y, print_loss=False):
    loss = 0
    global a, z, w, b
    
    g = 2*(X - y).reshape(1,-1).T

    loss = (y - X)**2
    if print_loss:
        print("Loss: ", (y - X)**2)
    
    n_weights, n_bias = [], []
    for x in range(len(w)):
        i = len(b) - 1 - x

        # Activation Function Derrivative [1xn]
        af_der = relu(z[i], True).reshape(1,-1).T  # Activation Function Derriv
        g = g * af_der
        
        # Derivative with respect to weight [1xn]  
        if i-1 < 0: w_der = y.reshape(1,-1).T
        else: w_der = a[i-1].reshape(1,-1).T  # Previous Layer Activation
        
        # Saving New Weights
        new_weights = w[i] - learning_rate * (w_der @ g.T)
        n_weights.append(new_weights)
        n_bias.append(b[i] - learning_rate * g.reshape(1,-1))

        g = w[i] @ g
  
    n_bias = list(reversed(n_bias))
    n_weights = list(reversed(n_weights))
#     for x in b: print(x.shape)
#     for x in n_bias: print(x.shape)
    w = n_weights
    b = n_bias
    return loss
    
X = forward_prop(np.array([0,1]))
back_prop(X, np.array([1]))




array([[0.69531709]])

In [89]:
from random import randint

reset()

def train(epochs, size=100):
    for i in range(epochs):
        tmp = 0.0
        for x in range(size):
            y1 = randint(0,1)
            y2 = randint(0,1)
            tmp += back_prop(forward_prop(np.array([y1,y2])), np.array([y1+y2])) 
        print("Loss: ", tmp/size)

train(40, 100)
print(forward_prop(np.array([0.2,0.3])))
print(forward_prop(np.array([0.7,0.2])))
print(forward_prop(np.array([1,0])))
print(forward_prop(np.array([1,1])))



Loss:  [[0.01012882]]
Loss:  [[0.0030969]]
Loss:  [[0.00153564]]
Loss:  [[0.0010704]]
Loss:  [[0.00059733]]
Loss:  [[0.00031151]]
Loss:  [[0.00016389]]
Loss:  [[9.43639402e-05]]
Loss:  [[5.51350155e-05]]
Loss:  [[2.90632903e-05]]
Loss:  [[1.86054637e-05]]
Loss:  [[1.34233439e-05]]
Loss:  [[6.97850596e-06]]
Loss:  [[3.12532169e-06]]
Loss:  [[1.56357969e-06]]
Loss:  [[1.11545628e-06]]
Loss:  [[6.49720387e-07]]
Loss:  [[3.28417706e-07]]
Loss:  [[1.74068532e-07]]
Loss:  [[1.11550649e-07]]
Loss:  [[6.29629962e-08]]
Loss:  [[2.28582996e-08]]
Loss:  [[1.45535779e-08]]
Loss:  [[8.99545748e-09]]
Loss:  [[4.46973198e-09]]
Loss:  [[2.09412185e-09]]
Loss:  [[1.12883647e-09]]
Loss:  [[5.55715176e-10]]
Loss:  [[2.59822014e-10]]
Loss:  [[1.8439068e-10]]
Loss:  [[1.02547773e-10]]
Loss:  [[5.24751536e-11]]
Loss:  [[3.27699111e-11]]
Loss:  [[1.93033879e-11]]
Loss:  [[1.38349843e-11]]
Loss:  [[5.59829559e-12]]
Loss:  [[3.09528791e-12]]
Loss:  [[1.75731129e-12]]
Loss:  [[8.52069558e-13]]
Loss:  [[5.610360

In [82]:
print(b)


[array([[1.44671871e-04, 9.67246506e-05, 1.85768508e-04]]), array([[ 5.30291522e-05, -1.06914399e-04,  5.60509843e-05]]), array([[-0.00031825, -0.00087005]]), array([[-0.00012256]])]


## Learning XOR

In [91]:
X = [
    [0,1],
    [0,0],
    [1,0],
    [1,1]
]

y = [1,0,1,0]

reset()

def train(epochs, size=100):
    for i in range(epochs):
        tmp = 0.0
        for x in range(size):
            y1 = randint(0,3)
            tmp += back_prop(forward_prop(np.array(X[y1])), np.array(y[y1])) 
        print("Loss: ", tmp/size)
      
train(20, 2000)

print(forward_prop(np.array([1,0])))
print(forward_prop(np.array([0,1])))
print(forward_prop(np.array([0,0])))
print(forward_prop(np.array([1,1])))




Loss:  [[0.06709958]]
Loss:  [[1.98819205e-09]]
Loss:  [[3.42828565e-19]]
Loss:  [[3.97647853e-29]]
Loss:  [[2.93843467e-31]]
Loss:  [[1.91873153e-31]]
Loss:  [[1.58143843e-31]]
Loss:  [[1.66801606e-31]]
Loss:  [[1.71022915e-31]]
Loss:  [[1.94534691e-31]]
Loss:  [[2.39242653e-31]]
Loss:  [[1.97108019e-31]]
Loss:  [[2.14980413e-31]]
Loss:  [[2.00562581e-31]]
Loss:  [[1.82810845e-31]]
Loss:  [[2.92957116e-31]]
Loss:  [[2.79730578e-31]]
Loss:  [[1.7166716e-31]]
Loss:  [[1.6312734e-31]]
Loss:  [[1.56257413e-31]]
[[1.]]
[[1.]]
[[6.00954158e-16]]
[[0]]
