In [1]:
import numpy as np
import math

# TEST
$h_1=0$ 

In [194]:
def relu(z, deriv=False):
    activations = []
    shape = z.shape
    z = z.flatten()
    if deriv:
        for i in range(len(z)):
            if z[i] >= 0:
                activations.append(1)
            else:
                activations.append(-0.2)
        return np.array(activations).reshape(shape)
    for i in range(len(z)):
        if z[i] > 0:
            activations.append(z[i])
        else:
            activations.append(-0.2 * z[i])
    return np.array(activations).reshape(shape)

In [113]:
def reset():
    global w, b
    w = [
        np.array(np.random.randn(6)).reshape(2,3),
        np.array(np.random.randn(9)).reshape(3,3),
        np.array(np.random.randn(6)).reshape(3,2),
        np.array(np.random.randn(2)).reshape(2,1)
    ]
    b = [
        np.array(np.zeros(3)),
        np.array(np.zeros(3)),
        np.array(np.zeros(2)),
        np.array(np.zeros(1))
    ]

# [previous, neuron_count]
w = [

]
b = [

]

reset()

for i in w: print(i)

[[ 0.47236408  0.35098556 -0.16282832]
 [ 1.4175084  -2.35780217  0.45368306]]
[[ 0.05750707 -0.39551893  0.43416338]
 [-0.42886034 -0.38810165  1.05099684]
 [ 0.38446359 -0.76753419 -0.4143932 ]]
[[-1.15432547  0.72548309]
 [ 0.9092547  -0.82310184]
 [-0.3468875   0.3337282 ]]
[[-1.1574449 ]
 [-0.91594885]]


In [4]:
np.array([[0,1]]) @ w[0]

array([[0.54105797, 0.41605256, 0.01360361]])

In [114]:
z = [
    
]
a = [
    
]

reset()

def forward_prop(X):
    h = X
    global a, z
    a,z  = [], []
    for i in range(len(w)):
        h = h @ w[i] # weigt * input
        h = h + b[i] # bias add
        z.append(h)
        h = relu(h) # Activation Function
        a.append(h)
    return h

forward_prop(np.array([0,1]))


array([0])

# Back Prop

for each layer

$g = loss'(X,y)$

## Step 1 ($a$ to $z$)

$g = relu'(z)$



## Step 2 ($z$ to $W$)

$g = relu'(z) * a_{L-1}$

# Dimensions

$g = [1\times2]$

## Step 1 Activation Function Derriv

$g = [1\times2]$


In [256]:
learning_rate = 0.2

reset()

def back_prop(X, y, print_loss=False):
    loss = 0
    global a, z, w, b
    
    g = (X - y).reshape(1,-1).T
    loss = 0.5*(y - X)**2
    
    if print_loss:
        print("Loss: ", (y - X)**2)
    
    n_weights, n_bias = [], []
    
    for x in range(len(w)):
        i = len(b) - 1 - x

        # Activation Function Derrivative [1xn]
        g = g * relu(z[i], True)  # Activation Function Derriv
        
        # Derivative with respect to weight [1xn]  
        if i-1 < 0: w_der = y.reshape(1,-1).T
        else: w_der = a[i-1].reshape(1,-1).T  # Previous Layer Activation
        
        
#         print(w_der.shape, g.shape)
#         print((w_der @ g).shape)
        
        # Change in Weights
        new_weights = w[i] - learning_rate * (w_der @ g)
        n_weights.append(new_weights)
        
        new_bias = b[i] - learning_rate * g
        n_bias.append(new_bias)
        
        g = g @ w[i].T 
    
    n_weights = list(reversed(n_weights))
    n_bias = list(reversed(n_bias))
    w = n_weights
    b = n_bias
    
    return loss
    

X = forward_prop(np.array([0,1]))
print(X)
back_prop(X, np.array([1]))

[0.00033035]


array([0.4996697])

In [188]:
from random import randint

def train(epochs, size=100):
    for i in range(epochs):
        tmp = 0.0
        for x in range(size):
            y1 = randint(0,1)
            y2 = randint(0,1)
            tmp += back_prop(forward_prop(np.array([y1,y2])), np.array([y1+y2]))[0]
        print("Loss: ", tmp/size)

reset()
train(20, 500)
print(forward_prop(np.array([0.2,0.3])))
print(forward_prop(np.array([0.7,0.2])))
print(forward_prop(np.array([1,0])))
print(forward_prop(np.array([1,1])))

Loss:  [0.40042846]
Loss:  [0.05717091]
Loss:  [0.03874792]
Loss:  [0.0339624]
Loss:  [0.0261027]
Loss:  [0.02398881]
Loss:  [0.02112197]
Loss:  [0.01880983]
Loss:  [0.01694079]
Loss:  [0.01456519]
Loss:  [0.01265015]
Loss:  [0.01115511]
Loss:  [0.01203928]
Loss:  [0.01059292]
Loss:  [0.00971486]
Loss:  [0.0081658]
Loss:  [0.00705318]
Loss:  [0.00686392]
Loss:  [0.00611966]
Loss:  [0.00571631]
[[0.55467714]]
[[0.99950418]]
[[1.1567219]]
[[1.94013978]]


## Learning XOR

In [264]:
X = [
    [0,1],
    [0,0],
    [1,0],
    [1,1]
]

y = [1,0,1,0]

reset()

def train(epochs, size=100):
    for i in range(epochs):
        tmp = 0.0
        for x in range(size):
            y1 = randint(0,3)
            tmp += back_prop(forward_prop(np.array(X[y1])), np.array(y[y1]))[0]
        print("Loss: ", tmp/size)
      

train(20, 100)

print(forward_prop(np.array([1,0])))
print(forward_prop(np.array([0,1])))
print(forward_prop(np.array([0,0])))
print(forward_prop(np.array([1,1])))

print(w)
print(b)

Loss:  [0.15050137]
Loss:  [0.12941549]
Loss:  [0.13089094]
Loss:  [0.12896175]
Loss:  [0.12088918]
Loss:  [0.12174382]
Loss:  [0.11548262]
Loss:  [0.10326216]
Loss:  [0.07147332]
Loss:  [0.03182517]
Loss:  [0.0037258]
Loss:  [0.00085587]
Loss:  [0.00044528]
Loss:  [0.00031997]
Loss:  [0.00018049]
Loss:  [0.00017935]
Loss:  [0.00011844]
Loss:  [9.35320416e-05]
Loss:  [5.53553604e-05]
Loss:  [3.18098264e-05]
[[0.99960762]]
[[1.00028389]]
[[0.0150068]]
[[7.92150614e-05]]
[array([[ 1.97054459, -2.81806191,  0.03650922],
       [ 0.29425528, -0.92453928,  0.92799386]]), array([[ 0.20280271,  0.41829016, -0.62599738],
       [ 1.84691646,  0.68244146, -0.96449574],
       [ 1.02034973,  0.52363776,  0.89989944]]), array([[-0.10206539, -2.20438863],
       [ 0.91434694,  1.10866309],
       [-0.31747786,  0.99122434]]), array([[ 0.85650762],
       [-2.5608622 ]])]
[array([[-0.60133739, -0.00860175,  0.01973175]]), array([[-1.37919203, -0.06200702,  0.05902828]]), array([[-0.84098286,  0.586

In [258]:
working_w_b = {
    "w": w,
    "b": b
}

print(working_w_b)

{'w': [array([[ 1.54876358, -1.24253546, -0.41267138],
       [ 1.05036975, -0.91747989,  1.00974905]]), array([[-1.2548782 , -1.40340579, -0.88367188],
       [ 0.20918457,  0.32485332, -1.09196149],
       [-0.62706676, -1.475977  ,  1.54952924]]), array([[-0.94844447, -0.63866621],
       [-1.28160641, -2.10228276],
       [ 0.16416751,  1.29274642]]), array([[ 0.67945281],
       [-2.88925098]])], 'b': [array([[-0.05793085,  0.34370978,  0.38956388]]), array([[ 0.05749785,  1.28978517, -0.29233234]]), array([[-0.12134365,  1.65705825]]), array([[-0.37683778]])]}


In [169]:
w = working_w_b["w"]
b = working_w_b["b"]

print(forward_prop(np.array([1,0])))
print(forward_prop(np.array([0,1])))
print(forward_prop(np.array([0,0])))
print(forward_prop(np.array([1,1])))

print(w)
print(b)

[[1.]]
[[1.]]
[[5.77118852e-16]]
[[7.68392101e-16]]
[array([[ 0.82497381,  0.59840391,  1.31815359],
       [-0.22509377,  1.19228404,  2.24951462]]), array([[ 0.33853337, -0.48228155, -1.63981744],
       [ 0.78615243, -0.48763467,  0.3400973 ],
       [ 0.93141037, -1.35151089,  0.62963734]]), array([[ 5.07610397e-01, -3.67255683e-01],
       [-1.36799822e-03, -4.70333681e-01],
       [-1.37615029e+00,  9.68110094e-01]]), array([[0.81541792],
       [0.96582707]])]
[array([[0.22509377, 0.10685884, 0.19480117]]), array([[0.01200832, 0.        , 0.37186151]]), array([[ 0.04306578, -0.02670464]]), array([[3.2272429e-16]])]
