In [1]:
import numpy as np
import math

# TEST
$h_1=0$ 

In [2]:
def relu(z, deriv=False):
    activations = []
    shape = z.shape
    z = z.flatten()
    if deriv:
        for i in range(len(z)):
            if z[i] >= 0:
                activations.append(1)
            else:
                activations.append(0)
        return np.array(activations).reshape(shape)
    for i in range(len(z)):
        if z[i] > 0:
            activations.append(z[i])
        else:
            activations.append(0)
    return np.array(activations).reshape(shape)

In [33]:
def reset():
    global w, b
    w = [
        np.array(np.random.rand(6)).reshape(2,3),
        np.array(np.random.rand(9)).reshape(3,3),
        np.array(np.random.rand(6)).reshape(3,2),
        np.array(np.random.rand(2)).reshape(2,1)
    ]
    b = [
        np.array(np.random.rand(3)),
        np.array(np.random.rand(3)),
        np.array(np.random.rand(2)),
        np.array(np.random.rand(1))
    ]

# [previous, neuron_count]
w = [
    np.array(np.random.rand(6)).reshape(2,3),
    np.array(np.random.rand(9)).reshape(3,3),
    np.array(np.random.rand(6)).reshape(3,2),
    np.array(np.random.rand(2)).reshape(2,1)
]
b = [
    np.array(np.random.rand(3)),
    np.array(np.random.rand(3)),
    np.array(np.random.rand(2)),
    np.array(np.random.rand(1))
]

for i in w: print(i)

[[0.26754037 0.4141417  0.63573997]
 [0.22918934 0.94005709 0.04360092]]
[[0.93913987 0.90593735 0.62291966]
 [0.11355432 0.21802018 0.12834518]
 [0.1881299  0.48095143 0.54786501]]
[[0.51232152 0.38836737]
 [0.96255943 0.02365192]
 [0.32203345 0.76508755]]
[[0.96871103]
 [0.09930695]]


In [4]:
np.array([[0,1]]) @ w[0]

array([[0.21441747, 0.58068606, 0.85106577]])

In [5]:
z = [
    
]
a = [
    
]


def forward_prop(X):
    h = X
    global a, z
    a,z  = [], []
    for i in range(len(w)):
        h = h @ w[i] # weigt * input
        h = h + b[i] # bias add
        z.append(h)
        h = relu(h) # Activation Function
        a.append(h)
    return h

forward_prop(np.array([0,1]))


array([31.33006967])

# Back Prop

for each layer

$g = loss'(X,y)$

## Step 1 ($a$ to $z$)

$g = relu'(z)$



## Step 2 ($z$ to $W$)

$g = relu'(z) * a_{L-1}$

# Dimensions

$g = [1\times2]$

## Step 1 Activation Function Derriv

$g = [1\times2]$


In [29]:
learning_rate = 0.002

reset()

def back_prop(X, y, print_loss=False):
    loss = 0
    global a, z, w
    
    g = 2*(X - y).reshape(1,-1).T

    loss = (y - X)**2
    if print_loss:
        print("Loss: ", (y - X)**2)
    
    n_weights = []
    for x in range(len(w)):
        i = len(b) - 1 - x

        # Activation Function Derrivative [1xn]
        af_der = relu(z[i], True).reshape(1,-1).T  # Activation Function Derriv
        g = g * af_der
        
        
        # Derivative with respect to weight [1xn]  
        if i-1 < 0: w_der = y.reshape(1,-1).T
        else: w_der = a[i-1].reshape(1,-1).T  # Previous Layer Activation
        
        # Change in Weights
        scalar = g
        # Saving New Weights
        new_weights = w[i] - learning_rate * (w_der @ g.T)
        n_weights.append(new_weights)
        g = w[i] @ g
    
    n_weights = list(reversed(n_weights))
    w = n_weights
    return loss
    

#         print("\nOld Weights: ", w[i-1], w[i-1].shape)
#         print("\nNew Weights: ", new_weights, new_weights.shape)
#         print("############################################################")

for i in range(20):
    X = forward_prop(np.array([0,1]))
    print(X)
    back_prop(X, np.array([1]))

[2.8424545]
[2.71496222]
[2.60433369]
[2.50723813]
[2.42119503]
[2.34431403]
[2.27512598]
[2.21246965]
[2.15541355]
[2.10320076]
[2.0552091]
[2.01092185]
[1.96990593]
[1.93179531]
[1.89627827]
[1.86308753]
[1.83199241]
[1.80279272]
[1.77531373]
[1.74940223]


In [30]:
from random import randint

reset()

def train(epochs, size=100):
    for i in range(epochs):
        tmp = 0.0
        for x in range(size):
            y1 = randint(0,1)
            y2 = randint(0,1)
            tmp += back_prop(forward_prop(np.array([y1,y2])), np.array([y1+y2])) 
        print("Loss: ", tmp/size)
      
train(40, 100)

Loss:  [0.64574296]
Loss:  [0.39980032]
Loss:  [0.45976417]
Loss:  [0.48856786]
Loss:  [0.50825224]
Loss:  [0.47954362]
Loss:  [0.39296417]
Loss:  [0.42215777]
Loss:  [0.40160614]
Loss:  [0.32443555]
Loss:  [0.36735106]
Loss:  [0.27118338]
Loss:  [0.28982061]
Loss:  [0.21946767]
Loss:  [0.17738216]
Loss:  [0.13553399]
Loss:  [0.13036952]
Loss:  [0.08162366]
Loss:  [0.06296159]
Loss:  [0.05615115]
Loss:  [0.02666766]
Loss:  [0.02569117]
Loss:  [0.01619464]
Loss:  [0.0082117]
Loss:  [0.00719509]
Loss:  [0.00493777]
Loss:  [0.00356099]
Loss:  [0.00242509]
Loss:  [0.00274931]
Loss:  [0.00259351]
Loss:  [0.00203652]
Loss:  [0.00237643]
Loss:  [0.0021581]
Loss:  [0.00221825]
Loss:  [0.0018314]
Loss:  [0.00205594]
Loss:  [0.00256404]
Loss:  [0.00217049]
Loss:  [0.00205945]
Loss:  [0.00180026]


In [31]:
print(forward_prop(np.array([0.2,0.3])))
print(forward_prop(np.array([0.7,0.2])))
print(forward_prop(np.array([1,0])))
print(forward_prop(np.array([1,1])))



[0.51980858]
[0.8844378]
[0.95490285]
[2.01427766]


## Learning XOR

In [34]:
X = [
    [0,1],
    [0,0],
    [1,0],
    [1,1]
]

y = [1,0,1,0]

reset()

def train(epochs, size=100):
    for i in range(epochs):
        tmp = 0.0
        for x in range(size):
            y1 = randint(0,3)
            tmp += back_prop(forward_prop(np.array(X[y1])), np.array(y[y1])) 
        print("Loss: ", tmp/size)
      
train(100, 1000)

print(forward_prop(np.array([1,0])))
print(forward_prop(np.array([0,1])))
print(forward_prop(np.array([0,0])))
print(forward_prop(np.array([1,1])))




Loss:  [0.4879567]
Loss:  [0.25986924]
Loss:  [0.25376168]
Loss:  [0.25609294]
Loss:  [0.25265645]
Loss:  [0.23578726]
Loss:  [0.2267871]
Loss:  [0.20987972]
Loss:  [0.19538341]
Loss:  [0.18155554]
Loss:  [0.17575018]
Loss:  [0.1799497]
Loss:  [0.17179148]
Loss:  [0.17219131]
Loss:  [0.16790021]
Loss:  [0.15809177]
Loss:  [0.15632871]
Loss:  [0.15152383]
Loss:  [0.15199152]
Loss:  [0.15513698]
Loss:  [0.17584591]
Loss:  [0.17684867]
Loss:  [0.17620493]
Loss:  [0.15471214]
Loss:  [0.15265165]
Loss:  [0.14830207]
Loss:  [0.1525435]
Loss:  [0.15116165]
Loss:  [0.17963072]
Loss:  [0.17397263]
Loss:  [0.16591043]
Loss:  [0.16880415]
Loss:  [0.17180674]
Loss:  [0.1585868]
Loss:  [0.16664021]
Loss:  [0.17319196]
Loss:  [0.16521052]
Loss:  [0.16584363]
Loss:  [0.16095915]
Loss:  [0.16890004]
Loss:  [0.16273996]
Loss:  [0.16492065]
Loss:  [0.16227448]
Loss:  [0.1647396]
Loss:  [0.17453722]
Loss:  [0.1676691]
Loss:  [0.16467034]
Loss:  [0.16388349]
Loss:  [0.15894318]
Loss:  [0.16847701]
Loss:  